deployment:
  image: "us-central1-docker.pkg.dev/molten-unison-401314/terraform-images/backend-terraform"
  tag: 105fd43792434e06787b977a7197ec5923b3b779
  container_port: 80
  name: "deployment-v1"
configMap:
  DB_USER: root
  DB_PASSWORD: "12345678"
  DB_NAME: terraform-db-backend
  DB_PATH: 10.230.221.5
  PORT: 80
  name: "config-v2"
service:
  service_port: 80
  target_port: 80
  type: ClusterIP
  name: "service-v1"
  IP: 34.128.155.141
issuer: 
  email: tventura@hermesv.io
  name: "issuer-v1"
certificate:
  name: "certificate-v1"
ingress:
  name: "ingress-v2"
domain: backend-kuber.master-vm.shop
name: "backend-terraform"
