apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: "{{ .Values.ingress.name }}"
  annotations:
    cert-manager.io/cluster-issuer: "{{ .Values.issuer.name }}"
    nginx.ingress.kubernetes.io/rewrite-target: /
    kubernetes.io/ingress.regional-static-ip-name: "{{ .Values.ingress.ip }}"
    kubernetes.io/ingress.class: "gce-internal"
spec:
  ingressClassName: nginx
  rules:
  - host: {{ .Values.domain }}
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: "{{ .Values.service.name }}"
            port:
              number: 80
  defaultBackend:
    service:
      name: "{{ .Values.service.name }}"
      port:
        number: 80
  tls:
    - hosts:
      -   {{ .Values.domain }}
      secretName: "{{ .Values.issuer.name }}"